In [66]:
#TASK - 1

import numpy as np
hrempId = np.arange(1,501)
print("HR Department employees:\n",hrempId)

HR Department employees:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144
 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162
 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180
 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198
 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216
 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234
 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252
 253 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270
 271 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306
 307 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324
 325 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342
 343 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360
 361 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378
 379 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396
 397 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414
 415 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432
 433 434 435 436 437 438 439 440 441 442 443 444 445 446 447 448 449 450
 451 452 453 454 455 456 457 458 459 460 461 462 463 464 465 466 467 468
 469 470 471 472 473 474 475 476 477 478 479 480 481 482 483 484 485 486
 487 488 489 490 491 492 493 494 495 496 497 498 499 500]

In [67]:
import numpy as np
fnempId = np.arange(501,1001)
print("FINANCE Department employees:\n",fnempId)

FINANCE Department employees:
 [ 501  502  503  504  505  506  507  508  509  510  511  512  513  514
  515  516  517  518  519  520  521  522  523  524  525  526  527  528
  529  530  531  532  533  534  535  536  537  538  539  540  541  542
  543  544  545  546  547  548  549  550  551  552  553  554  555  556
  557  558  559  560  561  562  563  564  565  566  567  568  569  570
  571  572  573  574  575  576  577  578  579  580  581  582  583  584
  585  586  587  588  589  590  591  592  593  594  595  596  597  598
  599  600  601  602  603  604  605  606  607  608  609  610  611  612
  613  614  615  616  617  618  619  620  621  622  623  624  625  626
  627  628  629  630  631  632  633  634  635  636  637  638  639  640
  641  642  643  644  645  646  647  648  649  650  651  652  653  654
  655  656  657  658  659  660  661  662  663  664  665  666  667  668
  669  670  671  672  673  674  675  676  677  678  679  680  681  682
  683  684  685  686  687  688  689  690  691  692  693  694  695  696
  697  698  699  700  701  702  703  704  705  706  707  708  709  710
  711  712  713  714  715  716  717  718  719  720  721  722  723  724
  725  726  727  728  729  730  731  732  733  734  735  736  737  738
  739  740  741  742  743  744  745  746  747  748  749  750  751  752
  753  754  755  756  757  758  759  760  761  762  763  764  765  766
  767  768  769  770  771  772  773  774  775  776  777  778  779  780
  781  782  783  784  785  786  787  788  789  790  791  792  793  794
  795  796  797  798  799  800  801  802  803  804  805  806  807  808
  809  810  811  812  813  814  815  816  817  818  819  820  821  822
  823  824  825  826  827  828  829  830  831  832  833  834  835  836
  837  838  839  840  841  842  843  844  845  846  847  848  849  850
  851  852  853  854  855  856  857  858  859  860  861  862  863  864
  865  866  867  868  869  870  871  872  873  874  875  876  877  878
  879  880  881  882  883  884  885  886  887  888  889  890  891  892
  893  894  895  896  897  898  899  900  901  902  903  904  905  906
  907  908  909  910  911  912  913  914  915  916  917  918  919  920
  921  922  923  924  925  926  927  928  929  930  931  932  933  934
  935  936  937  938  939  940  941  942  943  944  945  946  947  948
  949  950  951  952  953  954  955  956  957  958  959  960  961  962
  963  964  965  966  967  968  969  970  971  972  973  974  975  976
  977  978  979  980  981  982  983  984  985  986  987  988  989  990
  991  992  993  994  995  996  997  998  999 1000]

In [68]:
import numpy as np
itempId = np.arange(1001,1501)
print("IT Department employees:\n",itempId)

IT Department employees:
 [1001 1002 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014
 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028
 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042
 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056
 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070
 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084
 1085 1086 1087 1088 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098
 1099 1100 1101 1102 1103 1104 1105 1106 1107 1108 1109 1110 1111 1112
 1113 1114 1115 1116 1117 1118 1119 1120 1121 1122 1123 1124 1125 1126
 1127 1128 1129 1130 1131 1132 1133 1134 1135 1136 1137 1138 1139 1140
 1141 1142 1143 1144 1145 1146 1147 1148 1149 1150 1151 1152 1153 1154
 1155 1156 1157 1158 1159 1160 1161 1162 1163 1164 1165 1166 1167 1168
 1169 1170 1171 1172 1173 1174 1175 1176 1177 1178 1179 1180 1181 1182
 1183 1184 1185 1186 1187 1188 1189 1190 1191 1192 1193 1194 1195 1196
 1197 1198 1199 1200 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210
 1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224
 1225 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238
 1239 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252
 1253 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266
 1267 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280
 1281 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294
 1295 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308
 1309 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322
 1323 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335 1336
 1337 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350
 1351 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363 1364
 1365 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378
 1379 1380 1381 1382 1383 1384 1385 1386 1387 1388 1389 1390 1391 1392
 1393 1394 1395 1396 1397 1398 1399 1400 1401 1402 1403 1404 1405 1406
 1407 1408 1409 1410 1411 1412 1413 1414 1415 1416 1417 1418 1419 1420
 1421 1422 1423 1424 1425 1426 1427 1428 1429 1430 1431 1432 1433 1434
 1435 1436 1437 1438 1439 1440 1441 1442 1443 1444 1445 1446 1447 1448
 1449 1450 1451 1452 1453 1454 1455 1456 1457 1458 1459 1460 1461 1462
 1463 1464 1465 1466 1467 1468 1469 1470 1471 1472 1473 1474 1475 1476
 1477 1478 1479 1480 1481 1482 1483 1484 1485 1486 1487 1488 1489 1490
 1491 1492 1493 1494 1495 1496 1497 1498 1499 1500]

In [69]:
import numpy as np
slempId = np.arange(1501,2001)
print("SALES Department employees:\n",slempId)

SALES Department employees:
 [1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710
 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724
 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738
 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752
 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766
 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794
 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808
 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822
 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836
 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850
 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864
 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878
 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906
 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920
 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934
 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948
 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962
 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976
 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
 1991 1992 1993 1994 1995 1996 1997 1998 1999 2000]

In [71]:
#TASK 2 

import numpy as np
HR_sal = np.random.randint(25000,50000,500)
print("HR Employees Salaries:\n",HR_sal)
Finance_sal=HR_sal*1.25
print("Finance Employees Salaries:\n",Finance_sal)
Sales_sal=Finance_sal*0.5
print("Sales Employees Salaries:\n",Sales_sal)
IT_sal=HR_sal+5000
print("IT Employee Salaries:\n",IT_sal)

HR Employees Salaries:
 [40509 32691 34569 38505 33725 34903 34846 37095 31310 49301 27291 35820
 39374 45318 41300 29782 29102 47097 44875 27452 26459 31299 45192 44105
 26379 47602 26021 49121 30480 42857 36900 25568 40065 41314 37083 35363
 44434 31882 36813 29160 28616 35341 36837 42607 31714 48587 47730 34210
 27495 28039 35523 36057 31275 35574 26887 34500 33275 42283 29549 28970
 43488 42015 33548 29200 42562 42148 31028 26269 32240 28319 38900 34490
 37810 35760 29304 48309 35740 35538 47655 31583 29115 28055 47333 28619
 41744 43801 47821 36083 47649 38928 45092 38565 26015 30005 27942 45095
 48114 49450 31369 45694 28608 30216 35366 28420 48334 32543 44126 38351
 42368 39120 31702 26376 31001 46603 34580 35683 48920 30674 48024 35947
 47064 32127 34234 34109 28264 28357 43384 42290 46335 48030 42433 38793
 29853 45707 40005 39691 39744 49161 38012 25200 28259 26764 42131 28887
 45643 35942 36767 44084 32127 48463 36450 37707 43836 40806 43440 32693
 46529 28977 48454 38114 43782 40675 31052 28911 30338 47793 29095 47125
 36179 46048 36167 37633 26846 32545 39544 47824 30013 35358 34476 39845
 40545 28584 44853 30641 36232 27748 29737 29684 38433 32373 49770 31580
 29925 46535 27024 49888 32410 45114 25768 25028 37498 35211 49158 25211
 47773 36122 30915 38709 45454 36433 42399 35776 45617 42340 34589 28835
 44970 35582 42416 46610 34845 46387 35667 26296 49956 46019 28119 26029
 35213 42274 44556 30421 30717 45825 30077 48022 45688 36300 25172 48400
 40230 28121 37070 27936 28804 40453 32925 48315 43850 34330 33633 33325
 27927 39690 47462 35140 42490 46848 49582 36222 40906 41251 44994 36607
 27380 37430 26464 31541 26438 37563 29117 33240 27368 42548 29815 27511
 37178 43850 33965 38277 26270 27487 25857 48248 37993 48949 40299 41985
 32497 39267 28192 29529 48156 42348 29897 42679 27668 25079 37909 25260
 39928 42604 30375 31401 46172 32268 45307 46149 43815 30119 26129 39652
 26082 29818 41905 42316 37727 49783 38180 49878 32440 29108 28852 47357
 47132 27113 34416 30388 37680 36050 37010 29355 34917 37272 41879 37098
 28107 25770 38199 49023 38877 28871 46493 27414 30714 36737 37174 35938
 40048 39062 38896 38652 36236 32830 36987 43557 34628 49801 31169 37750
 39354 44016 41383 34434 33727 38228 42674 37986 47812 44500 33681 45179
 40247 29015 47604 36609 26952 36140 44038 42962 36856 43871 42855 25457
 27867 36736 31468 30928 27993 47728 47943 29590 29152 42324 46756 38543
 30376 45612 31334 45052 34710 43107 49154 34981 29684 29989 36592 31713
 29219 30919 46791 32591 37849 39115 41185 38349 33608 45765 47517 45532
 36838 40900 30258 45849 44722 25082 32265 46746 42051 31381 44753 41557
 36964 48968 42150 30245 42883 34721 37483 28063 35756 30846 40562 36954
 31896 45055 28922 40110 25258 48340 40652 26671 29895 42445 29600 45298
 48891 27201 45451 41723 38585 30020 48895 46316 40704 39057 29243 47498
 28400 46492 47728 40761 43108 36064 41459 41198 40951 42250 43178 29277
 39719 36377 28499 34710 34325 37203 41376 36200 48731 37297 27485 48754
 32730 30116 43831 34730 47022 39480 29864 40820]
Finance Employees Salaries:
 [50636.25 40863.75 43211.25 48131.25 42156.25 43628.75 43557.5  46368.75
 39137.5  61626.25 34113.75 44775.   49217.5  56647.5  51625.   37227.5
 36377.5  58871.25 56093.75 34315.   33073.75 39123.75 56490.   55131.25
 32973.75 59502.5  32526.25 61401.25 38100.   53571.25 46125.   31960.
 50081.25 51642.5  46353.75 44203.75 55542.5  39852.5  46016.25 36450.
 35770.   44176.25 46046.25 53258.75 39642.5  60733.75 59662.5  42762.5
 34368.75 35048.75 44403.75 45071.25 39093.75 44467.5  33608.75 43125.
 41593.75 52853.75 36936.25 36212.5  54360.   52518.75 41935.   36500.
 53202.5  52685.   38785.   32836.25 40300.   35398.75 48625.   43112.5
 47262.5  44700.   36630.   60386.25 44675.   44422.5  59568.75 39478.75
 36393.75 35068.75 59166.25 35773.75 52180.   54751.25 59776.25 45103.75
 59561.25 48660.   56365.   48206.25 32518.75 37506.25 34927.5  56368.75
 60142.5  61812.5  39211.25 57117.5  35760.   37770.   44207.5  35525.
 60417.5  40678.75 55157.5  47938.75 52960.   48900.   39627.5  32970.
 38751.25 58253.75 43225.   44603.75 61150.   38342.5  60030.   44933.75
 58830.   40158.75 42792.5  42636.25 35330.   35446.25 54230.   52862.5
 57918.75 60037.5  53041.25 48491.25 37316.25 57133.75 50006.25 49613.75
 49680.   61451.25 47515.   31500.   35323.75 33455.   52663.75 36108.75
 57053.75 44927.5  45958.75 55105.   40158.75 60578.75 45562.5  47133.75
 54795.   51007.5  54300.   40866.25 58161.25 36221.25 60567.5  47642.5
 54727.5  50843.75 38815.   36138.75 37922.5  59741.25 36368.75 58906.25
 45223.75 57560.   45208.75 47041.25 33557.5  40681.25 49430.   59780.
 37516.25 44197.5  43095.   49806.25 50681.25 35730.   56066.25 38301.25
 45290.   34685.   37171.25 37105.   48041.25 40466.25 62212.5  39475.
 37406.25 58168.75 33780.   62360.   40512.5  56392.5  32210.   31285.
 46872.5  44013.75 61447.5  31513.75 59716.25 45152.5  38643.75 48386.25
 56817.5  45541.25 52998.75 44720.   57021.25 52925.   43236.25 36043.75
 56212.5  44477.5  53020.   58262.5  43556.25 57983.75 44583.75 32870.
 62445.   57523.75 35148.75 32536.25 44016.25 52842.5  55695.   38026.25
 38396.25 57281.25 37596.25 60027.5  57110.   45375.   31465.   60500.
 50287.5  35151.25 46337.5  34920.   36005.   50566.25 41156.25 60393.75
 54812.5  42912.5  42041.25 41656.25 34908.75 49612.5  59327.5  43925.
 53112.5  58560.   61977.5  45277.5  51132.5  51563.75 56242.5  45758.75
 34225.   46787.5  33080.   39426.25 33047.5  46953.75 36396.25 41550.
 34210.   53185.   37268.75 34388.75 46472.5  54812.5  42456.25 47846.25
 32837.5  34358.75 32321.25 60310.   47491.25 61186.25 50373.75 52481.25
 40621.25 49083.75 35240.   36911.25 60195.   52935.   37371.25 53348.75
 34585.   31348.75 47386.25 31575.   49910.   53255.   37968.75 39251.25
 57715.   40335.   56633.75 57686.25 54768.75 37648.75 32661.25 49565.
 32602.5  37272.5  52381.25 52895.   47158.75 62228.75 47725.   62347.5
 40550.   36385.   36065.   59196.25 58915.   33891.25 43020.   37985.
 47100.   45062.5  46262.5  36693.75 43646.25 46590.   52348.75 46372.5
 35133.75 32212.5  47748.75 61278.75 48596.25 36088.75 58116.25 34267.5
 38392.5  45921.25 46467.5  44922.5  50060.   48827.5  48620.   48315.
 45295.   41037.5  46233.75 54446.25 43285.   62251.25 38961.25 47187.5
 49192.5  55020.   51728.75 43042.5  42158.75 47785.   53342.5  47482.5
 59765.   55625.   42101.25 56473.75 50308.75 36268.75 59505.   45761.25
 33690.   45175.   55047.5  53702.5  46070.   54838.75 53568.75 31821.25
 34833.75 45920.   39335.   38660.   34991.25 59660.   59928.75 36987.5
 36440.   52905.   58445.   48178.75 37970.   57015.   39167.5  56315.
 43387.5  53883.75 61442.5  43726.25 37105.   37486.25 45740.   39641.25
 36523.75 38648.75 58488.75 40738.75 47311.25 48893.75 51481.25 47936.25
 42010.   57206.25 59396.25 56915.   46047.5  51125.   37822.5  57311.25
 55902.5  31352.5  40331.25 58432.5  52563.75 39226.25 55941.25 51946.25
 46205.   61210.   52687.5  37806.25 53603.75 43401.25 46853.75 35078.75
 44695.   38557.5  50702.5  46192.5  39870.   56318.75 36152.5  50137.5
 31572.5  60425.   50815.   33338.75 37368.75 53056.25 37000.   56622.5
 61113.75 34001.25 56813.75 52153.75 48231.25 37525.   61118.75 57895.
 50880.   48821.25 36553.75 59372.5  35500.   58115.   59660.   50951.25
 53885.   45080.   51823.75 51497.5  51188.75 52812.5  53972.5  36596.25
 49648.75 45471.25 35623.75 43387.5  42906.25 46503.75 51720.   45250.
 60913.75 46621.25 34356.25 60942.5  40912.5  37645.   54788.75 43412.5
 58777.5  49350.   37330.   51025.  ]
Sales Employees Salaries:
 [25318.125 20431.875 21605.625 24065.625 21078.125 21814.375 21778.75
 23184.375 19568.75  30813.125 17056.875 22387.5   24608.75  28323.75
 25812.5   18613.75  18188.75  29435.625 28046.875 17157.5   16536.875
 19561.875 28245.    27565.625 16486.875 29751.25  16263.125 30700.625
 19050.    26785.625 23062.5   15980.    25040.625 25821.25  23176.875
 22101.875 27771.25  19926.25  23008.125 18225.    17885.    22088.125
 23023.125 26629.375 19821.25  30366.875 29831.25  21381.25  17184.375
 17524.375 22201.875 22535.625 19546.875 22233.75  16804.375 21562.5
 20796.875 26426.875 18468.125 18106.25  27180.    26259.375 20967.5
 18250.    26601.25  26342.5   19392.5   16418.125 20150.    17699.375
 24312.5   21556.25  23631.25  22350.    18315.    30193.125 22337.5
 22211.25  29784.375 19739.375 18196.875 17534.375 29583.125 17886.875
 26090.    27375.625 29888.125 22551.875 29780.625 24330.    28182.5
 24103.125 16259.375 18753.125 17463.75  28184.375 30071.25  30906.25
 19605.625 28558.75  17880.    18885.    22103.75  17762.5   30208.75
 20339.375 27578.75  23969.375 26480.    24450.    19813.75  16485.
 19375.625 29126.875 21612.5   22301.875 30575.    19171.25  30015.
 22466.875 29415.    20079.375 21396.25  21318.125 17665.    17723.125
 27115.    26431.25  28959.375 30018.75  26520.625 24245.625 18658.125
 28566.875 25003.125 24806.875 24840.    30725.625 23757.5   15750.
 17661.875 16727.5   26331.875 18054.375 28526.875 22463.75  22979.375
 27552.5   20079.375 30289.375 22781.25  23566.875 27397.5   25503.75
 27150.    20433.125 29080.625 18110.625 30283.75  23821.25  27363.75
 25421.875 19407.5   18069.375 18961.25  29870.625 18184.375 29453.125
 22611.875 28780.    22604.375 23520.625 16778.75  20340.625 24715.
 29890.    18758.125 22098.75  21547.5   24903.125 25340.625 17865.
 28033.125 19150.625 22645.    17342.5   18585.625 18552.5   24020.625
 20233.125 31106.25  19737.5   18703.125 29084.375 16890.    31180.
 20256.25  28196.25  16105.    15642.5   23436.25  22006.875 30723.75
 15756.875 29858.125 22576.25  19321.875 24193.125 28408.75  22770.625
 26499.375 22360.    28510.625 26462.5   21618.125 18021.875 28106.25
 22238.75  26510.    29131.25  21778.125 28991.875 22291.875 16435.
 31222.5   28761.875 17574.375 16268.125 22008.125 26421.25  27847.5
 19013.125 19198.125 28640.625 18798.125 30013.75  28555.    22687.5
 15732.5   30250.    25143.75  17575.625 23168.75  17460.    18002.5
 25283.125 20578.125 30196.875 27406.25  21456.25  21020.625 20828.125
 17454.375 24806.25  29663.75  21962.5   26556.25  29280.    30988.75
 22638.75  25566.25  25781.875 28121.25  22879.375 17112.5   23393.75
 16540.    19713.125 16523.75  23476.875 18198.125 20775.    17105.
 26592.5   18634.375 17194.375 23236.25  27406.25  21228.125 23923.125
 16418.75  17179.375 16160.625 30155.    23745.625 30593.125 25186.875
 26240.625 20310.625 24541.875 17620.    18455.625 30097.5   26467.5
 18685.625 26674.375 17292.5   15674.375 23693.125 15787.5   24955.
 26627.5   18984.375 19625.625 28857.5   20167.5   28316.875 28843.125
 27384.375 18824.375 16330.625 24782.5   16301.25  18636.25  26190.625
 26447.5   23579.375 31114.375 23862.5   31173.75  20275.    18192.5
 18032.5   29598.125 29457.5   16945.625 21510.    18992.5   23550.
 22531.25  23131.25  18346.875 21823.125 23295.    26174.375 23186.25
 17566.875 16106.25  23874.375 30639.375 24298.125 18044.375 29058.125
 17133.75  19196.25  22960.625 23233.75  22461.25  25030.    24413.75
 24310.    24157.5   22647.5   20518.75  23116.875 27223.125 21642.5
 31125.625 19480.625 23593.75  24596.25  27510.    25864.375 21521.25
 21079.375 23892.5   26671.25  23741.25  29882.5   27812.5   21050.625
 28236.875 25154.375 18134.375 29752.5   22880.625 16845.    22587.5
 27523.75  26851.25  23035.    27419.375 26784.375 15910.625 17416.875
 22960.    19667.5   19330.    17495.625 29830.    29964.375 18493.75
 18220.    26452.5   29222.5   24089.375 18985.    28507.5   19583.75
 28157.5   21693.75  26941.875 30721.25  21863.125 18552.5   18743.125
 22870.    19820.625 18261.875 19324.375 29244.375 20369.375 23655.625
 24446.875 25740.625 23968.125 21005.    28603.125 29698.125 28457.5
 23023.75  25562.5   18911.25  28655.625 27951.25  15676.25  20165.625
 29216.25  26281.875 19613.125 27970.625 25973.125 23102.5   30605.
 26343.75  18903.125 26801.875 21700.625 23426.875 17539.375 22347.5
 19278.75  25351.25  23096.25  19935.    28159.375 18076.25  25068.75
 15786.25  30212.5   25407.5   16669.375 18684.375 26528.125 18500.
 28311.25  30556.875 17000.625 28406.875 26076.875 24115.625 18762.5
 30559.375 28947.5   25440.    24410.625 18276.875 29686.25  17750.
 29057.5   29830.    25475.625 26942.5   22540.    25911.875 25748.75
 25594.375 26406.25  26986.25  18298.125 24824.375 22735.625 17811.875
 21693.75  21453.125 23251.875 25860.    22625.    30456.875 23310.625
 17178.125 30471.25  20456.25  18822.5   27394.375 21706.25  29388.75
 24675.    18665.    25512.5  ]
IT Employee Salaries:
 [45509 37691 39569 43505 38725 39903 39846 42095 36310 54301 32291 40820
 44374 50318 46300 34782 34102 52097 49875 32452 31459 36299 50192 49105
 31379 52602 31021 54121 35480 47857 41900 30568 45065 46314 42083 40363
 49434 36882 41813 34160 33616 40341 41837 47607 36714 53587 52730 39210
 32495 33039 40523 41057 36275 40574 31887 39500 38275 47283 34549 33970
 48488 47015 38548 34200 47562 47148 36028 31269 37240 33319 43900 39490
 42810 40760 34304 53309 40740 40538 52655 36583 34115 33055 52333 33619
 46744 48801 52821 41083 52649 43928 50092 43565 31015 35005 32942 50095
 53114 54450 36369 50694 33608 35216 40366 33420 53334 37543 49126 43351
 47368 44120 36702 31376 36001 51603 39580 40683 53920 35674 53024 40947
 52064 37127 39234 39109 33264 33357 48384 47290 51335 53030 47433 43793
 34853 50707 45005 44691 44744 54161 43012 30200 33259 31764 47131 33887
 50643 40942 41767 49084 37127 53463 41450 42707 48836 45806 48440 37693
 51529 33977 53454 43114 48782 45675 36052 33911 35338 52793 34095 52125
 41179 51048 41167 42633 31846 37545 44544 52824 35013 40358 39476 44845
 45545 33584 49853 35641 41232 32748 34737 34684 43433 37373 54770 36580
 34925 51535 32024 54888 37410 50114 30768 30028 42498 40211 54158 30211
 52773 41122 35915 43709 50454 41433 47399 40776 50617 47340 39589 33835
 49970 40582 47416 51610 39845 51387 40667 31296 54956 51019 33119 31029
 40213 47274 49556 35421 35717 50825 35077 53022 50688 41300 30172 53400
 45230 33121 42070 32936 33804 45453 37925 53315 48850 39330 38633 38325
 32927 44690 52462 40140 47490 51848 54582 41222 45906 46251 49994 41607
 32380 42430 31464 36541 31438 42563 34117 38240 32368 47548 34815 32511
 42178 48850 38965 43277 31270 32487 30857 53248 42993 53949 45299 46985
 37497 44267 33192 34529 53156 47348 34897 47679 32668 30079 42909 30260
 44928 47604 35375 36401 51172 37268 50307 51149 48815 35119 31129 44652
 31082 34818 46905 47316 42727 54783 43180 54878 37440 34108 33852 52357
 52132 32113 39416 35388 42680 41050 42010 34355 39917 42272 46879 42098
 33107 30770 43199 54023 43877 33871 51493 32414 35714 41737 42174 40938
 45048 44062 43896 43652 41236 37830 41987 48557 39628 54801 36169 42750
 44354 49016 46383 39434 38727 43228 47674 42986 52812 49500 38681 50179
 45247 34015 52604 41609 31952 41140 49038 47962 41856 48871 47855 30457
 32867 41736 36468 35928 32993 52728 52943 34590 34152 47324 51756 43543
 35376 50612 36334 50052 39710 48107 54154 39981 34684 34989 41592 36713
 34219 35919 51791 37591 42849 44115 46185 43349 38608 50765 52517 50532
 41838 45900 35258 50849 49722 30082 37265 51746 47051 36381 49753 46557
 41964 53968 47150 35245 47883 39721 42483 33063 40756 35846 45562 41954
 36896 50055 33922 45110 30258 53340 45652 31671 34895 47445 34600 50298
 53891 32201 50451 46723 43585 35020 53895 51316 45704 44057 34243 52498
 33400 51492 52728 45761 48108 41064 46459 46198 45951 47250 48178 34277
 44719 41377 33499 39710 39325 42203 46376 41200 53731 42297 32485 53754
 37730 35116 48831 39730 52022 44480 34864 45820]

In [72]:
#TASK - 3

import numpy as np
Tot_HR=np.sum(HR_sal)
Tot_Finance=np.sum(Finance_sal)
Tot_IT=sum(IT_sal)
Tot_Sales=sum(Sales_sal)
print("Total HR salaries: ",Tot_HR)
print("Total Finance salaries: ",Tot_Finance)
print("Total IT salaries: ",Tot_IT)
print("Total Sales salaries: ",Tot_Sales)

Total HR salaries:  18630159
Total Finance salaries:  23287698.75
Total IT salaries:  21130159
Total Sales salaries:  11643849.375

In [73]:
print("Finance depertment cost more to the company:")

Finance depertment cost more to the company:

In [80]:
#TASK - 4
sal_HR=np.sort(HR_sal)[-1:-11:-1]
print("Top 10 salary of HR Department:\n",sal_HR)
print("Sum of top 10 salary of HR Department: ",sal_HR.sum())

sal_Finance=np.sort(Finance_sal)[-1:-11:-1]
print("Top 10 salary of Finance Department:\n",sal_Finance)
print("Sum of top 10 salary of Finance Department: ",sal_Finance.sum())

sal_Sales=np.sort(Sales_sal)[-1:-11:-1]
print("Top 10 salary of Sales Department:\n",sal_Sales)
print("Sum of top 10 salary of Sales Department: ",sal_Sales.sum())

sal_IT=np.sort(IT_sal)[-1:-11:-1]
print("Top 10 salary of IT Department:\n",sal_IT)
print("Sum of top 10 salary of IT Department: ",sal_IT.sum())

Top 10 salary of HR Department:
 [49956 49888 49878 49801 49783 49770 49582 49450 49301 49161]
Sum of top 10 salary of HR Department:  496570
Top 10 salary of Finance Department:
 [62445.   62360.   62347.5  62251.25 62228.75 62212.5  61977.5  61812.5
 61626.25 61451.25]
Sum of top 10 salary of Finance Department:  620712.5
Top 10 salary of Sales Department:
 [31222.5   31180.    31173.75  31125.625 31114.375 31106.25  30988.75
 30906.25  30813.125 30725.625]
Sum of top 10 salary of Sales Department:  310356.25
Top 10 salary of IT Department:
 [54956 54888 54878 54801 54783 54770 54582 54450 54301 54161]
Sum of top 10 salary of IT Department:  546570

In [81]:
#TASK - 5

salhr=np.count_nonzero(HR_sal>45000)
salfin=np.count_nonzero(Finance_sal>45000)
salsal=np.count_nonzero(Sales_sal>45000)
salit=np.count_nonzero(IT_sal>45000)
totalemp= salhr+salfin+salsal+salit
print("Total number of employees with salary more than 45000 that are eligible for 10% increment: ",totalemp)

Total number of employees with salary more than 45000 that are eligible for 10% increment:  565

In [86]:
#TASK - 6

sales=np.where(Sales_sal<20000, Sales_sal*1.20, Sales_sal)
Sales_sal=sales.copy()
print("Sales employees:\n",Sales_sal)
print("Employees with 20% increment:\n", sales)

Sales employees:
 [25318.125 20431.875 21605.625 24065.625 21078.125 21814.375 21778.75
 23184.375 23482.5   30813.125 20468.25  22387.5   24608.75  28323.75
 25812.5   22336.5   21826.5   29435.625 28046.875 20589.    23813.1
 23474.25  28245.    27565.625 23741.1   29751.25  23418.9   30700.625
 22860.    26785.625 23062.5   23011.2   25040.625 25821.25  23176.875
 22101.875 27771.25  23911.5   23008.125 21870.    21462.    22088.125
 23023.125 26629.375 23785.5   30366.875 29831.25  21381.25  20621.25
 21029.25  22201.875 22535.625 23456.25  22233.75  20165.25  21562.5
 20796.875 26426.875 22161.75  21727.5   27180.    26259.375 20967.5
 21900.    26601.25  26342.5   23271.    23642.1   20150.    21239.25
 24312.5   21556.25  23631.25  22350.    21978.    30193.125 22337.5
 22211.25  29784.375 23687.25  21836.25  21041.25  29583.125 21464.25
 26090.    27375.625 29888.125 22551.875 29780.625 24330.    28182.5
 24103.125 23413.5   22503.75  20956.5   28184.375 30071.25  30906.25
 23526.75  28558.75  21456.    22662.    22103.75  21315.    30208.75
 20339.375 27578.75  23969.375 26480.    24450.    23776.5   23738.4
 23250.75  29126.875 21612.5   22301.875 30575.    23005.5   30015.
 22466.875 29415.    20079.375 21396.25  21318.125 21198.    21267.75
 27115.    26431.25  28959.375 30018.75  26520.625 24245.625 22389.75
 28566.875 25003.125 24806.875 24840.    30725.625 23757.5   22680.
 21194.25  20073.    26331.875 21665.25  28526.875 22463.75  22979.375
 27552.5   20079.375 30289.375 22781.25  23566.875 27397.5   25503.75
 27150.    20433.125 29080.625 21732.75  30283.75  23821.25  27363.75
 25421.875 23289.    21683.25  22753.5   29870.625 21821.25  29453.125
 22611.875 28780.    22604.375 23520.625 20134.5   20340.625 24715.
 29890.    22509.75  22098.75  21547.5   24903.125 25340.625 21438.
 28033.125 22980.75  22645.    20811.    22302.75  22263.    24020.625
 20233.125 31106.25  23685.    22443.75  29084.375 20268.    31180.
 20256.25  28196.25  23191.2   22525.2   23436.25  22006.875 30723.75
 22689.9   29858.125 22576.25  23186.25  24193.125 28408.75  22770.625
 26499.375 22360.    28510.625 26462.5   21618.125 21626.25  28106.25
 22238.75  26510.    29131.25  21778.125 28991.875 22291.875 23666.4
 31222.5   28761.875 21089.25  23426.1   22008.125 26421.25  27847.5
 22815.75  23037.75  28640.625 22557.75  30013.75  28555.    22687.5
 22654.8   30250.    25143.75  21090.75  23168.75  20952.    21603.
 25283.125 20578.125 30196.875 27406.25  21456.25  21020.625 20828.125
 20945.25  24806.25  29663.75  21962.5   26556.25  29280.    30988.75
 22638.75  25566.25  25781.875 28121.25  22879.375 20535.    23393.75
 23817.6   23655.75  23794.2   23476.875 21837.75  20775.    20526.
 26592.5   22361.25  20633.25  23236.25  27406.25  21228.125 23923.125
 23643.    20615.25  23271.3   30155.    23745.625 30593.125 25186.875
 26240.625 20310.625 24541.875 21144.    22146.75  30097.5   26467.5
 22422.75  26674.375 20751.    22571.1   23693.125 22734.    24955.
 26627.5   22781.25  23550.75  28857.5   20167.5   28316.875 28843.125
 27384.375 22589.25  23516.1   24782.5   23473.8   22363.5   26190.625
 26447.5   23579.375 31114.375 23862.5   31173.75  20275.    21831.
 21639.    29598.125 29457.5   20334.75  21510.    22791.    23550.
 22531.25  23131.25  22016.25  21823.125 23295.    26174.375 23186.25
 21080.25  23193.    23874.375 30639.375 24298.125 21653.25  29058.125
 20560.5   23035.5   22960.625 23233.75  22461.25  25030.    24413.75
 24310.    24157.5   22647.5   20518.75  23116.875 27223.125 21642.5
 31125.625 23376.75  23593.75  24596.25  27510.    25864.375 21521.25
 21079.375 23892.5   26671.25  23741.25  29882.5   27812.5   21050.625
 28236.875 25154.375 21761.25  29752.5   22880.625 20214.    22587.5
 27523.75  26851.25  23035.    27419.375 26784.375 22911.3   20900.25
 22960.    23601.    23196.    20994.75  29830.    29964.375 22192.5
 21864.    26452.5   29222.5   24089.375 22782.    28507.5   23500.5
 28157.5   21693.75  26941.875 30721.25  21863.125 22263.    22491.75
 22870.    23784.75  21914.25  23189.25  29244.375 20369.375 23655.625
 24446.875 25740.625 23968.125 21005.    28603.125 29698.125 28457.5
 23023.75  25562.5   22693.5   28655.625 27951.25  22573.8   20165.625
 29216.25  26281.875 23535.75  27970.625 25973.125 23102.5   30605.
 26343.75  22683.75  26801.875 21700.625 23426.875 21047.25  22347.5
 23134.5   25351.25  23096.25  23922.    28159.375 21691.5   25068.75
 22732.2   30212.5   25407.5   20003.25  22421.25  26528.125 22200.
 28311.25  30556.875 20400.75  28406.875 26076.875 24115.625 22515.
 30559.375 28947.5   25440.    24410.625 21932.25  29686.25  21300.
 29057.5   29830.    25475.625 26942.5   22540.    25911.875 25748.75
 25594.375 26406.25  26986.25  21957.75  24824.375 22735.625 21374.25
 21693.75  21453.125 23251.875 25860.    22625.    30456.875 23310.625
 20613.75  30471.25  20456.25  22587.    27394.375 21706.25  29388.75
 24675.    22398.    25512.5  ]
Employees with 20% increment:
 [25318.125 20431.875 21605.625 24065.625 21078.125 21814.375 21778.75
 23184.375 23482.5   30813.125 20468.25  22387.5   24608.75  28323.75
 25812.5   22336.5   21826.5   29435.625 28046.875 20589.    23813.1
 23474.25  28245.    27565.625 23741.1   29751.25  23418.9   30700.625
 22860.    26785.625 23062.5   23011.2   25040.625 25821.25  23176.875
 22101.875 27771.25  23911.5   23008.125 21870.    21462.    22088.125
 23023.125 26629.375 23785.5   30366.875 29831.25  21381.25  20621.25
 21029.25  22201.875 22535.625 23456.25  22233.75  20165.25  21562.5
 20796.875 26426.875 22161.75  21727.5   27180.    26259.375 20967.5
 21900.    26601.25  26342.5   23271.    23642.1   20150.    21239.25
 24312.5   21556.25  23631.25  22350.    21978.    30193.125 22337.5
 22211.25  29784.375 23687.25  21836.25  21041.25  29583.125 21464.25
 26090.    27375.625 29888.125 22551.875 29780.625 24330.    28182.5
 24103.125 23413.5   22503.75  20956.5   28184.375 30071.25  30906.25
 23526.75  28558.75  21456.    22662.    22103.75  21315.    30208.75
 20339.375 27578.75  23969.375 26480.    24450.    23776.5   23738.4
 23250.75  29126.875 21612.5   22301.875 30575.    23005.5   30015.
 22466.875 29415.    20079.375 21396.25  21318.125 21198.    21267.75
 27115.    26431.25  28959.375 30018.75  26520.625 24245.625 22389.75
 28566.875 25003.125 24806.875 24840.    30725.625 23757.5   22680.
 21194.25  20073.    26331.875 21665.25  28526.875 22463.75  22979.375
 27552.5   20079.375 30289.375 22781.25  23566.875 27397.5   25503.75
 27150.    20433.125 29080.625 21732.75  30283.75  23821.25  27363.75
 25421.875 23289.    21683.25  22753.5   29870.625 21821.25  29453.125
 22611.875 28780.    22604.375 23520.625 20134.5   20340.625 24715.
 29890.    22509.75  22098.75  21547.5   24903.125 25340.625 21438.
 28033.125 22980.75  22645.    20811.    22302.75  22263.    24020.625
 20233.125 31106.25  23685.    22443.75  29084.375 20268.    31180.
 20256.25  28196.25  23191.2   22525.2   23436.25  22006.875 30723.75
 22689.9   29858.125 22576.25  23186.25  24193.125 28408.75  22770.625
 26499.375 22360.    28510.625 26462.5   21618.125 21626.25  28106.25
 22238.75  26510.    29131.25  21778.125 28991.875 22291.875 23666.4
 31222.5   28761.875 21089.25  23426.1   22008.125 26421.25  27847.5
 22815.75  23037.75  28640.625 22557.75  30013.75  28555.    22687.5
 22654.8   30250.    25143.75  21090.75  23168.75  20952.    21603.
 25283.125 20578.125 30196.875 27406.25  21456.25  21020.625 20828.125
 20945.25  24806.25  29663.75  21962.5   26556.25  29280.    30988.75
 22638.75  25566.25  25781.875 28121.25  22879.375 20535.    23393.75
 23817.6   23655.75  23794.2   23476.875 21837.75  20775.    20526.
 26592.5   22361.25  20633.25  23236.25  27406.25  21228.125 23923.125
 23643.    20615.25  23271.3   30155.    23745.625 30593.125 25186.875
 26240.625 20310.625 24541.875 21144.    22146.75  30097.5   26467.5
 22422.75  26674.375 20751.    22571.1   23693.125 22734.    24955.
 26627.5   22781.25  23550.75  28857.5   20167.5   28316.875 28843.125
 27384.375 22589.25  23516.1   24782.5   23473.8   22363.5   26190.625
 26447.5   23579.375 31114.375 23862.5   31173.75  20275.    21831.
 21639.    29598.125 29457.5   20334.75  21510.    22791.    23550.
 22531.25  23131.25  22016.25  21823.125 23295.    26174.375 23186.25
 21080.25  23193.    23874.375 30639.375 24298.125 21653.25  29058.125
 20560.5   23035.5   22960.625 23233.75  22461.25  25030.    24413.75
 24310.    24157.5   22647.5   20518.75  23116.875 27223.125 21642.5
 31125.625 23376.75  23593.75  24596.25  27510.    25864.375 21521.25
 21079.375 23892.5   26671.25  23741.25  29882.5   27812.5   21050.625
 28236.875 25154.375 21761.25  29752.5   22880.625 20214.    22587.5
 27523.75  26851.25  23035.    27419.375 26784.375 22911.3   20900.25
 22960.    23601.    23196.    20994.75  29830.    29964.375 22192.5
 21864.    26452.5   29222.5   24089.375 22782.    28507.5   23500.5
 28157.5   21693.75  26941.875 30721.25  21863.125 22263.    22491.75
 22870.    23784.75  21914.25  23189.25  29244.375 20369.375 23655.625
 24446.875 25740.625 23968.125 21005.    28603.125 29698.125 28457.5
 23023.75  25562.5   22693.5   28655.625 27951.25  22573.8   20165.625
 29216.25  26281.875 23535.75  27970.625 25973.125 23102.5   30605.
 26343.75  22683.75  26801.875 21700.625 23426.875 21047.25  22347.5
 23134.5   25351.25  23096.25  23922.    28159.375 21691.5   25068.75
 22732.2   30212.5   25407.5   20003.25  22421.25  26528.125 22200.
 28311.25  30556.875 20400.75  28406.875 26076.875 24115.625 22515.
 30559.375 28947.5   25440.    24410.625 21932.25  29686.25  21300.
 29057.5   29830.    25475.625 26942.5   22540.    25911.875 25748.75
 25594.375 26406.25  26986.25  21957.75  24824.375 22735.625 21374.25
 21693.75  21453.125 23251.875 25860.    22625.    30456.875 23310.625
 20613.75  30471.25  20456.25  22587.    27394.375 21706.25  29388.75
 24675.    22398.    25512.5  ]

In [89]:
# TASK 7

newDup=slempId.copy()
#print(newDup)
newDup=np.delete(newDup, np.where(newDup>=1996))
#print(newDup)
new=np.arange(2001,2006)
newDup=np.append(newDup,new)
print(newDup)

[1501 1502 1503 1504 1505 1506 1507 1508 1509 1510 1511 1512 1513 1514
 1515 1516 1517 1518 1519 1520 1521 1522 1523 1524 1525 1526 1527 1528
 1529 1530 1531 1532 1533 1534 1535 1536 1537 1538 1539 1540 1541 1542
 1543 1544 1545 1546 1547 1548 1549 1550 1551 1552 1553 1554 1555 1556
 1557 1558 1559 1560 1561 1562 1563 1564 1565 1566 1567 1568 1569 1570
 1571 1572 1573 1574 1575 1576 1577 1578 1579 1580 1581 1582 1583 1584
 1585 1586 1587 1588 1589 1590 1591 1592 1593 1594 1595 1596 1597 1598
 1599 1600 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612
 1613 1614 1615 1616 1617 1618 1619 1620 1621 1622 1623 1624 1625 1626
 1627 1628 1629 1630 1631 1632 1633 1634 1635 1636 1637 1638 1639 1640
 1641 1642 1643 1644 1645 1646 1647 1648 1649 1650 1651 1652 1653 1654
 1655 1656 1657 1658 1659 1660 1661 1662 1663 1664 1665 1666 1667 1668
 1669 1670 1671 1672 1673 1674 1675 1676 1677 1678 1679 1680 1681 1682
 1683 1684 1685 1686 1687 1688 1689 1690 1691 1692 1693 1694 1695 1696
 1697 1698 1699 1700 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710
 1711 1712 1713 1714 1715 1716 1717 1718 1719 1720 1721 1722 1723 1724
 1725 1726 1727 1728 1729 1730 1731 1732 1733 1734 1735 1736 1737 1738
 1739 1740 1741 1742 1743 1744 1745 1746 1747 1748 1749 1750 1751 1752
 1753 1754 1755 1756 1757 1758 1759 1760 1761 1762 1763 1764 1765 1766
 1767 1768 1769 1770 1771 1772 1773 1774 1775 1776 1777 1778 1779 1780
 1781 1782 1783 1784 1785 1786 1787 1788 1789 1790 1791 1792 1793 1794
 1795 1796 1797 1798 1799 1800 1801 1802 1803 1804 1805 1806 1807 1808
 1809 1810 1811 1812 1813 1814 1815 1816 1817 1818 1819 1820 1821 1822
 1823 1824 1825 1826 1827 1828 1829 1830 1831 1832 1833 1834 1835 1836
 1837 1838 1839 1840 1841 1842 1843 1844 1845 1846 1847 1848 1849 1850
 1851 1852 1853 1854 1855 1856 1857 1858 1859 1860 1861 1862 1863 1864
 1865 1866 1867 1868 1869 1870 1871 1872 1873 1874 1875 1876 1877 1878
 1879 1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892
 1893 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906
 1907 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920
 1921 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934
 1935 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948
 1949 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962
 1963 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976
 1977 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990
 1991 1992 1993 1994 1995 2001 2002 2003 2004 2005]

In [ ]:
# Additional Questions

In [97]:
# TASK- 8

total_hr=np.sum(HR_sal)
total_sales=np.sum(Sales_sal)

percen=(total_sales/total_hr)*100
print("Total salary of HR department is greater than Sales department by %f %%" %percen)
avrg_hr=np.mean(HR_sal)
print("Average salary of HR department is: ",avrg_hr)
avrg_sales=np.mean(Sales_sal)
print("Average salary of Sales department is: ",avrg_sales)

Total salary of HR department is greater than Sales department by 65.932825 %
Average salary of HR department is:  37260.318
Average salary of Sales department is:  24566.7801

In [119]:
# TASK- 9

sumofemp=np.where(np.logical_and(Finance_sal>=50000, Finance_sal<=55000))
res=np.count_nonzero(sumofemp)
print("Number of employees from Finance Department salary between 50000-55000 are: ",res)

Number of employees from Finance Department salary between 50000-55000 are:  77
(array([  0,  14,  29,  32,  33,  43,  57,  60,  61,  64,  65,  84,  85,
       108, 126, 127, 130, 134, 142, 152, 153, 154, 160, 161, 180, 210,
       213, 218, 229, 240, 245, 248, 256, 260, 261, 273, 277, 286, 287,
       293, 295, 301, 308, 314, 315, 334, 348, 355, 362, 366, 372, 379,
       381, 382, 393, 401, 414, 421, 428, 431, 434, 436, 442, 447, 450,
       453, 459, 464, 471, 472, 474, 475, 476, 477, 478, 486, 494, 499],
      dtype=int64),)

In [112]:
pwd

'C:\\Users\\Manish'

In [117]:
# TASK 10

from numpy import genfromtxt

emp_details= genfromtxt('DS1_C4_S1_Numpy_PracticeBrief.csv', delimiter=',', skip_header=1)
print("Employees :\n", emp_details)
avrg_age= np.mean(emp_details)
print("Average age: ",avrg_age)

Employees :
 [[ 1. 22.]
 [ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 8. 23.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [13. 22.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [18. 22.]
 [19. 25.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [23. 24.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [34. 24.]
 [35. 24.]
 [36. 23.]
 [37. 28.]
 [38. 28.]
 [39. 22.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [47. 22.]
 [48. 23.]
 [49. 32.]
 [50. 34.]]
Average age:  26.88

In [123]:
# TASK- 11

from numpy import genfromtxt

ind=np.where(emp_details[:,1]>25)
print("Employees aged greater than 25:\n",emp_details[ind])

Employees aged greater than 25:
 [[ 2. 27.]
 [ 3. 31.]
 [ 4. 29.]
 [ 5. 27.]
 [ 6. 26.]
 [ 7. 27.]
 [ 9. 27.]
 [10. 32.]
 [11. 28.]
 [12. 27.]
 [14. 27.]
 [15. 35.]
 [16. 33.]
 [17. 28.]
 [20. 27.]
 [21. 37.]
 [22. 27.]
 [24. 27.]
 [25. 28.]
 [26. 26.]
 [27. 27.]
 [28. 27.]
 [29. 29.]
 [30. 49.]
 [31. 26.]
 [32. 32.]
 [33. 26.]
 [37. 28.]
 [38. 28.]
 [40. 26.]
 [41. 32.]
 [42. 35.]
 [43. 33.]
 [44. 31.]
 [45. 30.]
 [46. 36.]
 [49. 32.]
 [50. 34.]]

In [7]:
# TASK- 12

import numpy as np
from numpy import genfromtxt
emp_details= genfromtxt('DS1_C4_S1_Numpy_PracticeBrief.csv', delimiter=',', skip_header=1)
#res=np.where(np.logical_and(Age>=30, Age<=35))
res=np.where(np.logical_and(emp_details[:,1]>30,emp_details[:,1]<35))
print(emp_details[res])

[[ 3. 31.]
 [10. 32.]
 [16. 33.]
 [32. 32.]
 [41. 32.]
 [43. 33.]
 [44. 31.]
 [49. 32.]
 [50. 34.]]